"""Eingebauter Notfall-Katalog bekannter Wertkarten.

Grobe Hausnummern in EUR (Stand der Erstellung, Zustand ~played bis NM).
Er dient nur als Fallback, solange kein Scryfall-Spiegel geladen wurde
(`mtg-scout preise --aktualisieren`). Reale Preise schwanken stark -
die Zahlen sind fuer eine Groessenordnung gedacht, nicht fuer eine Kalkulation.
"""

from __future__ import annotations

from typing import Dict, Tuple

# name -> (EUR, Reserved List)
FALLBACK_CARDS: Dict[str, Tuple[float, bool]] = {
    # --- Power 9 -----------------------------------------------------------
    "Black Lotus": (25000.0, True),
    "Ancestral Recall": (9000.0, True),
    "Time Walk": (5500.0, True),
    "Mox Sapphire": (7000.0, True),
    "Mox Jet": (5500.0, True),
    "Mox Ruby": (4500.0, True),
    "Mox Pearl": (3500.0, True),
    "Mox Emerald": (3500.0, True),
    "Timetwister": (3500.0, True),
    # --- weitere Vintage-Ikonen -------------------------------------------
    "Mishra's Workshop": (5000.0, True),
    "Bazaar of Baghdad": (2500.0, True),
    "Library of Alexandria": (1400.0, True),
    "The Tabernacle at Pendrell Vale": (6000.0, True),
    "Juzam Djinn": (900.0, True),
    "Serra Angel": (25.0, False),
    "Shivan Dragon": (30.0, False),
    "Chaos Orb": (3500.0, True),
    "Falling Star": (900.0, True),
    "Gaea's Cradle": (450.0, True),
    "Serra's Sanctum": (300.0, True),
    "Time Vault": (600.0, True),
    "Candelabra of Tawnos": (400.0, True),
    "Copy Artifact": (120.0, True),
    "Wheel of Fortune": (200.0, True),
    "Mana Drain": (400.0, True),
    "Mana Crypt": (110.0, False),
    "Grim Monolith": (90.0, True),
    "Lion's Eye Diamond": (300.0, True),
    "Imperial Seal": (250.0, False),
    "Diamond Valley": (900.0, True),
    "Moat": (900.0, True),
    "Nether Void": (350.0, True),
    "Chains of Mephistopheles": (450.0, True),
    "Karakas": (120.0, True),
    "City of Traitors": (120.0, True),
    "Elephant Graveyard": (100.0, True),
    "Mishra's Factory": (12.0, False),
    # --- Dual Lands (Revised und aelter) -----------------------------------
    "Underground Sea": (900.0, True),
    "Volcanic Island": (700.0, True),
    "Tropical Island": (500.0, True),
    "Tundra": (450.0, True),
    "Badlands": (400.0, True),
    "Bayou": (450.0, True),
    "Taiga": (350.0, True),
    "Savannah": (350.0, True),
    "Scrubland": (350.0, True),
    "Plateau": (300.0, True),
    # --- Reserved-List-Klassiker ------------------------------------------
    "Survival of the Fittest": (120.0, True),
    "Null Rod": (60.0, True),
    "Sliver Queen": (150.0, True),
    "Intuition": (60.0, True),
    "Metalworker": (60.0, True),
    "Stasis": (40.0, True),
    "Berserk": (150.0, True),
    "The Abyss": (900.0, True),
    "Guardian Beast": (350.0, True),
    "Eureka": (300.0, True),
    "Land Tax": (25.0, True),
    "Mana Vault": (35.0, False),
    # --- moderne Wertkarten ------------------------------------------------
    "Force of Will": (90.0, False),
    "Ragavan, Nimble Pilferer": (55.0, False),
    "The One Ring": (55.0, False),
    "Orcish Bowmasters": (35.0, False),
    "Tarmogoyf": (20.0, False),
    "Liliana of the Veil": (30.0, False),
    "Snapcaster Mage": (25.0, False),
    "Jace, the Mind Sculptor": (35.0, False),
    "Cavern of Souls": (45.0, False),
    "Ancient Tomb": (45.0, False),
    "Wasteland": (45.0, False),
    "Rishadan Port": (40.0, False),
    "Sensei's Divining Top": (25.0, False),
    "Aether Vial": (25.0, False),
    "Chalice of the Void": (40.0, False),
    "Force of Negation": (25.0, False),
    "Urza's Saga": (40.0, False),
    "Misty Rainforest": (20.0, False),
    "Scalding Tarn": (20.0, False),
    "Verdant Catacombs": (20.0, False),
    "Polluted Delta": (20.0, False),
    "Flooded Strand": (20.0, False),
    "Windswept Heath": (18.0, False),
    "Bloodstained Mire": (18.0, False),
    "Wooded Foothills": (18.0, False),
    "Marsh Flats": (18.0, False),
    "Arid Mesa": (18.0, False),
    "Mox Diamond": (350.0, True),
    "Mox Opal": (40.0, False),
    "Dark Confidant": (20.0, False),
    "Thoughtseize": (18.0, False),
    "Sheoldred, the Apocalypse": (35.0, False),
    "Atraxa, Grand Unifier": (30.0, False),
    "Dockside Extortionist": (60.0, False),
    "Jeweled Lotus": (35.0, False),
    "Gaea's Will": (20.0, False),
    "Solitude": (45.0, False),
    "Fury": (35.0, False),
    "Grief": (25.0, False),
    "Endurance": (25.0, False),
    "Minsc & Boo, Timeless Heroes": (20.0, False),
    "Yawgmoth, Thran Physician": (25.0, False),
    "Nadu, Winged Wisdom": (10.0, False),
    "Wrenn and Six": (45.0, False),
    "Underworld Breach": (20.0, False),
    "Fierce Guardianship": (25.0, False),
    "Deflecting Swat": (15.0, False),
    "Mana Confluence": (15.0, False),
    "Horizon Canopy": (15.0, False),
    "Grove of the Burnwillows": (25.0, False),
    "Phyrexian Dreadnought": (60.0, True),
    "Vampiric Tutor": (25.0, False),
    "Demonic Tutor": (25.0, False),
    "Cyclonic Rift": (15.0, False),
    "Rhystic Study": (25.0, False),
    "Smothering Tithe": (20.0, False),
    "Mystic Remora": (10.0, False),
    "Craterhoof Behemoth": (20.0, False),
    "Doubling Season": (35.0, False),
    "Mana Reflection": (25.0, False),
    "Sylvan Library": (35.0, False),
}
